### PR TITLE
chore(version): bump libzbc versions

### PR DESCRIPTION
**Pull request by componentDidMount**
to support counting down retries added in https://github.com/zeebe-io/zbc-go/commit/4b8b596c3270cb8402dca1a41053d84951aafcd5 in the node client

### CODE REVIEW

**Comment by felix-mueller** [comment]
@menski not sure what is our process for updating the libzbc version?

**Comment by menski** [comment]
I think it's fine to do a release with this feature included until will release Zeebe 0.11.0

@componentDidMount the linux lib is missing in the pull request. Could you add it?

**Comment by componentDidMount** [comment]
@menski I tried, but there seems to be no diff, I did not yet fully understand why, I will look into it again.

**Comment by menski** [comment]
Okay then let me check. No worries. I will poke Sam to do a release afterwards.

**Comment by felix-mueller** [comment]
Do we still need this PR or were so latest changes of the other pull request enough?

**Comment by componentDidMount** [comment]
The other PR was unrelated to this one, so we still need it, or a new one where also the updated linux lib is present, I sadly cannot build it, or rather whatever I build there, the linux lib is not different from what we already have here.

Would be interesting to think about how to add some automation for always getting the latest lib release, now that we have tests we can at least guarantee that the newest lib always still does the intended stuff with the js wrapped around.

**Comment by felix-mueller** [comment]
@menski can you bump the libzbc versions? do we have a build for this?

**Comment by componentDidMount** [comment]
@menski I was building the lib like this:
```sh
$ ~/Go/bin/xgo -buildmode=c-shared --targets=*/amd64 github.com/zeebe-io/libzbc
```
the output log looks like this:
```sh
Checking docker installation...
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false

Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/zeebe-io/libzbc...
Fetching main repository github.com/zeebe-io/libzbc...
github.com/zeebe-io/libzbc (download)
Compiling for linux/amd64...
Compiling for windows-4.0/amd64...
Compiling for darwin-10.6/amd64...
Cleaning up build environment...
```
I attach the built files here.





[lib.zip](https://github.com/zeebe-io/zbc-node/files/2140085/lib.zip)

**Comment by componentDidMount** [comment]
@menski I did not update zbc-go individually, the xgo command is fetching libzbc from github `github.com/zeebe-io/libzbc` and takes revision feaff78ce7cbf8bbc491d33a55397890ead99cea from zbc-go (as defined in the Gopkg.lock) perhaps thats why. I did not know that I need to update the zbc-go, I thought its the latest already in `github.com/zeebe-io/libzbc`. Should I try updating it by hand and rebuilding?

**Comment by menski** [comment]
If it is okay for you to wait til next Monday, I would stop working on this now, as we will release a new version beginning next week to support Zeebe 0.11.0.

**Comment by componentDidMount** [comment]
Sure no problem, still funny though that the retries work with the darwin lib after I run the build command.

**Comment by menski** [comment]
Yeah that's what I also don't understand but I'm also not an expert of go dependency management.

**Pull request closed without merging**
